Web.Site.WebUI/Areas/Common/Controllers/DashboardController.cs
using Core.Service.Authen;
using Framework.Tool.Operator;
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Web.Mvc;
using Web.Site.WebUI.Common;

namespace Web.Site.WebUI.Areas.Common.Controllers
{
    [PartCreationPolicy(CreationPolicy.NonShared)]
    public class DashboardController : AdminController
    {
        [Import]
        private IUserService _userService { get; set; }
        //
        // GET: /Admin/Dashboard/
        public ActionResult Index()
        {
            var user = OperatorProvider.Provider.GetCurrent();
            if(user.IsFirstLogin)
            {
                return RedirectToAction("UserProfile");
            }
            else
            {
                return View();
            }
        }

        public ActionResult UserProfile()
        {
            ViewBag.User= OperatorProvider.Provider.GetCurrent().UserId;
            return View();
        }

    }
}

Web.Site.WebUI/Areas/Core/Controllers/ModuleController.cs
using Core.Service;
using Domain.Site.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Site.WebUI.Areas.Core.Controllers
{
    [Export]
    [PartCreationPolicy(CreationPolicy.NonShared)]
    public class ModuleController : Controller
    {
        [Import]
        private IModuleService _moduleService { get; set; }
        // GET: Core/Module
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetModuleListByQuery(ModuleQueryModel query)
        {
            return Json(_moduleService.GetModuleListByQuery(query));
        }

        [HttpPost]
        public ActionResult GetAllModule()
        {
            return Json(_moduleService.GetAllModuleList());
        }

        [HttpPost]
        public ActionResult GetLayerKeyValue()
        {
            return Json(_moduleService.GetLayerKeyValue());
        }
        [HttpPost]
        public ActionResult GetParentModuleKeyValue(int layer)
        {
            return Json(_moduleService.GetParentModuleKeyValue(layer));
        }

        [HttpPost]
        public ActionResult CreateModule(ModuleViewModel model)
        {
            return Json(_moduleService.CreateModule(model));
        }
    }
}

Web.Site.WebUI/Areas/Core/Controllers/UserController.cs
using Core.Service.Authen;
using Domain.Site.Models;
using Framework.Common.FileHelper;
using Framework.Tool.Operator;
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Web.Site.WebUI.Areas.Core.Controllers
{
    [Export]
    [PartCreationPolicy(CreationPolicy.NonShared)]
    public class UserController : Controller
    {
        [Import]
        private IUserService _userService { get; set; }
        // GET: System/User
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadUserPhoto(UserPhotoViewModel model)
        {
            model.FileName= System.Guid.NewGuid() + "." + HttpContext.Request.Files["file"].FileName.Split('.')[1];
            model.FilePath = Request.PhysicalApplicationPath + "image\\main\\userProfile\\";
            model.File.SaveAs(model.FilePath+model.FileName);
            return Json(_userService.UploadUserPhoto(model));
        }

        [HttpPost]
        public ActionResult GetUserProfile(int userId)
        {
            return Json(_userService.GetUserProfileById(userId));
        }
        [HttpPost]
        public ActionResult GetUserAccountById(int userId)
        {
            return Json(_userService.GetUserAccountById(userId));
        }

        [HttpPost]
        public ActionResult EditUserProfile(UserProfileViewModel model)
        {
            return Json(_userService.UpdateUserProfile(model));
        }
        [HttpPost]
        public ActionResult GetUserListByQuery(UserSearchViewModel query)
        {
           return Json(_userService.GetUserListByQuery(query));
        }

        [HttpPost]
        public ActionResult CreateUser(UserAccountViewModel model)
        {
            return Json(_userService.CreateUser(model));
        }

        [HttpPost]
        public ActionResult ChangePwd(UserAccountViewModel model)
        {
            return Json(_userService.ChangeUserPassWordBySystemUser(model));
        }
        [HttpPost]
        public ActionResult DeleteUser(int userId)
        {
            return Json(_userService.DeleteUser(userId));
        }
    }
}

Web.Site.WebUI/Areas/Common/Views/Shared/_HeaderMenu.cshtml
<header class="lyear-layout-header">
    <nav class="navbar navbar-default">
        <div class="topbar">

            <div class="topbar-left">
                <div class="lyear-aside-toggler">
                    <span class="lyear-toggler-bar"></span>
                    <span class="lyear-toggler-bar"></span>
                    <span class="lyear-toggler-bar"></span>
                </div>
                <span class="navbar-page-title" id="clock" />
            </div>

            <ul class="topbar-right">
                <li class="dropdown dropdown-profile">
                    <a href="javascript:void(0)" data-toggle="dropdown">
                        <img class="img-avatar img-avatar-48 m-r-10" id="header-userName-alt" src="~/image/main/userProfile.jpg" />
                        <span id="header-userName"> </span></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right">
                        <li> <a href="@Url.Action("UserProfile", "Dashboard", new { Area = "Common" })"><i class="mdi mdi-account"></i> 个人信息</a> </li>
                        <li class="divider"></li>
                        <li> <a href="@Url.Action("SignOut", "Login", new { Area = "Common" })"><i class="mdi mdi-logout-variant"></i> 退出登录</a> </li>
                    </ul>
                </li>
            </ul>

        </div>
    </nav>
   
</header>
<script src="~/Scripts/new/md5.js"></script>
<script>
    var photoPath = "/image/main/userProfile/";
    var attime;
    function clock() {
        var time = new Date();
        attime = time.toLocaleString();
        document.getElementById("clock").innerText = attime;
    }
    setInterval(clock, 1000);

    function getCookiesByName(name) {
        var arr;
        if (arr = document.cookie.match("pubser_loginuserkey")) {
            var obj = arr['input'];
            var index = obj.lastIndexOf("=");
            obj = obj.substring(index + 1, obj.length);
            var cookies = JSON.parse(obj);
            return cookies[name];
        }
        return null;
    }

    function getUserName() {
        let userName = getCookiesByName('LoginName');
        if (userName && userName != "") {
            let photo = getCookiesByName('PhotoPath');
            if (!photo) {
                photo = "userProfile.jpg";
            }
            document.getElementById("header-userName").innerHTML = userName + '<span class="caret">';
            document.getElementById("header-userName-alt").innerText = userName;
            document.getElementById("header-userName-alt").src = photoPath + photo;
        }
        else {
            window.location.href = "@Url.Action("index", "Account", new { Area = "Common" })";
        }
    }

    getUserName();
    setInterval(getUserName, 60*1000);
</script>

Web.Site.WebUI/Areas/Common/Views/Shared/_MainLayout.cshtml
@using Web.Site.WebUI.Extension.MvcHelper
@{
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <title>智慧项目管理</title>
    <link rel="icon" href="~/image/main/logo-mini.ico" type="image/ico">
    <meta name="keywords" content="智慧项目管理">
    <meta name="description" content="智慧项目管理">
    <meta name="author" content="wen.wen">
    @Styles.Render("~/bundles/css/cssBase")
</head>
<body>
    @Scripts.Render("~/bundles/scripts/jsBase")
    @Scripts.Render("~/bundles/scripts/jsNotify")

    <div style="background:#FCFCFC;width:100%;height:100%">
        <!--Header-Part-->
        @*@Html.Partial("_HeaderMenu")*@
        @Html.Partial("_HeaderMenu")
        <!--Header-Part-->


        @Html.Partial("_SidebarMenu")
        <!--main-container-part-->
        <main class="lyear-layout-content">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </main>
        <!--end-main-container-part-->
    </div>



    @RenderSection("scripts", required: false)
    @Html.RenderScriptBlocks()
    <script src="~/Scripts/new/layout.js"></script>
</body>
</html>

Web.Site.WebUI/Areas/Common/Views/Shared/_SidebarMenu.cshtml
<aside class="lyear-layout-sidebar">
    <div id="logo" class="sidebar-header">
        <a href="@Url.Action("Index", "Dashboard", new { Area = "Common" })"><img src="~/image/main/logo-sidebar.png" title="智慧项目管理" alt="智慧项目管理" /></a>
    </div>
    <div class="lyear-layout-sidebar-scroll">
        <nav class="sidebar-main">
            <ul class="nav nav-drawer" id="home_menu_list">
                <li class="nav-item active"> <a href="@Url.Action("Index", "Dashboard", new { Area = "Common" })"><i class="mdi mdi-home"></i> 首页</a> </li>
                @* 后期重构可配置化 *@
                <li class="nav-item nav-item-has-subnav">
                    <a href="javascript:void(0)"><i class="mdi mdi-widgets"></i>系统模块</a>
                    <ul class="nav nav-subnav">
                        <li> <a href="@Url.Action("Index", "Module", new { Area = "Core" })">模块管理</a> </li>
                        <li> <a href="lyear_ui_buttons.html">角色管理</a> </li>
                        <li> <a href="@Url.Action("Index", "User", new { Area = "Core" })">用户管理</a> </li>
                    </ul>
                </li>
                <li class="nav-item nav-item-has-subnav">
                    <a href="javascript:void(0)"><i class="mdi mdi-widgets"></i>项目模块</a>
                    <ul class="nav nav-subnav">
                        <li> <a href="@Url.Action("Index", "ProjectManager", new { Area = "Project" })">项目管理</a> </li>
                        <li> <a href="lyear_ui_buttons.html">系数配置</a> </li>
                        <li> <a href="lyear_ui_buttons.html">公式配置</a> </li>
                    </ul>
                </li>
                <li class="nav-item nav-item-has-subnav">
                    <a href="javascript:void(0)"><i class="mdi mdi-widgets"></i>申报模块</a>
                    <ul class="nav nav-subnav">
                        <li> <a href="lyear_ui_buttons.html">考勤记录</a></li>
                        <li> <a href="lyear_ui_buttons.html">请假申请</a> </li>
                        <li> <a href="lyear_ui_buttons.html">加班申请</a> </li>
                        <li> <a href="lyear_ui_buttons.html">物资申请</a> </li>
                        <li> <a href="lyear_ui_buttons.html">差旅申请</a> </li>
                        <li> <a href="lyear_ui_buttons.html">项目申报</a> </li>
                    </ul>
                </li>
                <li class="nav-item nav-item-has-subnav">
                    <a href="javascript:void(0)"><i class="mdi mdi-widgets"></i>财务模块</a>
                    <ul class="nav nav-subnav">
                        <li> <a href="lyear_ui_buttons.html">物资列表</a> </li>
                        <li> <a href="lyear_ui_buttons.html">个人支出列表</a> </li>
                        <li> <a href="lyear_ui_buttons.html">个人提成列表</a> </li>
                        <li> <a href="lyear_ui_buttons.html">项目财报</a> </li>
                    </ul>
                </li>
                <li>
                    <a href="lyear_ui_buttons.html"><i class="mdi mdi-widgets"></i>报表模块</a>
                </li>
                <li>
                    <a href="lyear_ui_buttons.html"><i class="mdi mdi-widgets"></i>消息模块</a>
                </li>
                @* end menu *@
            </ul>
        </nav>
        <div class="sidebar-footer">
            <p class="copyright">Copyright &copy; 2019. wen.wen All rights reserved.</p>
        </div>
    </div>

</aside>